sources:
  - ./Sources/Core
templates:
  include:
    - ./Codegen/Templates
  exclude:
    - ./Codegen/Templates/Shared
output:
  path: ./Codegen/Generated/FacebookCore
  link:
    project: ./FacebookSwift.xcodeproj
    target: FacebookCore
    group: Codegen/Generated
