swiftlint_version: 0.26.0

included:
- Sources
- Samples
- Tests

excluded:
- Pods
- Carthage
- Carthage/facebook-ios-sdk/samples
- Carthage/facebook-ios-sdk/vendor
- Vendor

cyclomatic_complexity: 11
indentation: 2
large_tuple: 3
line_length: 120

disabled_rules:
- class_delegate_protocol # TODO: Move to Opt In
- identifier_name # TODO: Move to Opt In
- number_separator
- todo # TODO: Move to Opt In
- weak_delegate # TODO: Move to Opt In

opt_in_rules:
- block_based_kvo
- closing_brace
- closure_end_indentation
- closure_parameter_position
- closure_spacing
- colon
- comma
- compiler_protocol_init
- control_statement
- custom_rules
- cyclomatic_complexity
- discarded_notification_center_observer
- discouraged_direct_init
- dynamic_inline
- empty_enum_arguments
- empty_parameters
- empty_parentheses_with_trailing_closure
- explicit_init
- file_length
- for_where
- force_cast
- force_try
- function_body_length
- function_parameter_count
- generic_type_name
- implicit_getter
- implicit_return
- is_disjoint
- joined_default_parameter
- large_tuple
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- legacy_nsgeometry_functions
- line_length
- literal_expression_end_indentation
- mark
- multiple_closures_with_trailing_closure
- nesting
- nimble_operator
- no_fallthrough_only
- notification_center_detachment
- opening_brace
- operator_usage_whitespace
- operator_whitespace
- private_over_fileprivate
- private_unit_test
- protocol_property_accessors_order
- redundant_discardable_let
- redundant_nil_coalescing
- redundant_optional_initialization
- redundant_set_access_control
- redundant_string_enum_value
- redundant_void_return
- return_arrow_whitespace
- shorthand_operator
- sorted_imports
- statement_position
- superfluous_disable_command
- switch_case_alignment
- syntactic_sugar
- trailing_comma
- trailing_newline
- trailing_semicolon
- trailing_whitespace
- type_body_length
- type_name
- unneeded_break_in_switch
- unneeded_parentheses_in_closure_argument
- untyped_error_in_catch
- unused_closure_parameter
- unused_enumerated
- unused_optional_binding
- valid_ibinspectable
- vertical_parameter_alignment
- vertical_whitespace
- void_return
- xctfail_message
