swiftlint_version: 0.26.0

included:
- Sources
- Samples
- Tests

excluded:
- Pods
- Carthage
- Carthage/facebook-ios-sdk/samples
- Carthage/facebook-ios-sdk/vendor
- Vendor

indentation: 2
line_length: 140
