# Environment
language: objective-c
os: osx
osx_image: xcode10.1
cache:
  - bundler
  - cocoapods
env:
  global:
    - XCODE_WORKSPACE=FacebookSwift.xcworkspace

# Branch Builds
branches:
  only:
    - master
    - release-1.0
    - core-conversion

# Build Stages
stages:
  - name: analysis
  - name: test

# Build Jobs
jobs:
  include:
    - stage: analysis
      name: Analysis
    - stage: test
      name: Test
      script: sh scripts/travis/test.sh

# Scripts
before_install: sh scripts/travis/before_install.sh
install: sh scripts/travis/install.sh
script: sh scripts/travis/script.sh
