branches:
  only:
    - master
language: objective-c
os: osx
osx_image: xcode10
cache:
  - cocoapods
env:
  matrix:
    - TEST_TYPE=iOS
    - TEST_TYPE=Lint
    - TEST_TYPE=Samples
    - TEST_TYPE=CocoaPods
    - TEST_TYPE=Carthage
before_install: sh Scripts/travis/before_install.sh
install: sh Scripts/travis/install_dependencies.sh
script: sh Scripts/travis/script.sh
